export const EXCEPTIONS = {
  EMAIL_CONFLICT: 'EMAIL_CONFLICT',
  PHONE_CONFLICT: 'PHONE_CONFLICT',
  NOT_FOUND: 'NOT_FOUND',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PHONE: 'INVALID_PHONE',
  CATEGORY_HAS_PRODUCTS: 'CATEGORY_HAS_PRODUCTS',
  STORE_ID_REQUIRED: 'STORE_ID_REQUIRED',
  NAME_EXISTED: 'NAME_EXISTED',
  ACCOUNT_NOT_ACTIVE: 'ACCOUNT_NOT_ACTIVE',
  INVALID_DEVICE_TOKEN: 'INVALID_DEVICE_TOKEN',

};
