export const MERCHANTS_EXCEPTIONS = {
  EMAIL_CONFLICT: 'EMAIL_CONFLICT',
  PHONE_CONFLICT: 'PHONE_CONFLICT',
  NOT_FOUND: 'NOT_FOUND',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PHONE: 'INVALID_PHONE',
};
